apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: v1-
namespace: color-palette

# Base resources
resources:
  - ../../base

# Patches
images:
  - name: REPLACED_BY_OVERLAY
    newName: <YOUR_ECR_REPO>
    newTag: v1
