apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: v2-
namespace: color-palette

resources:
  - ../../base

images:
  - name: color-palette
    newName: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/eks-ci-secure
    newTag: v2